### ISSUE TITLE
Resizing window ?

### ISSUE THREAD

**Issue by erwan35** [charlesfleche/lpd8-editor#12]
Hello,

Thanks to your help, i was able to successfully compile your software. But now, I got another prob.

I cannot resize the window so i's not fitting my screen. My screen resolution is 1920x1080.

![toobig](https://cloud.githubusercontent.com/assets/4410119/25790958/50a29e94-33bd-11e7-9ac9-8acf8fc5104b.png)

Cheers
Erwan

**Comment by charlesfleche** [comment]
Thanks for the report, @erwan35. It's indeed a problem. I'll run your distro (Ubuntu 16.04 + mate) in a VM and see how it goes.

**Comment by charlesfleche** [comment]
![virtualbox_ubuntu mate 16 04](https://cloud.githubusercontent.com/assets/2563098/25983128/efd75288-36a7-11e7-807c-435671d4d43b.png)
Layout is still bad in 1366x768 on Mate for v0.0.3 : on it ! :-)

**Comment by charlesfleche** [comment]
OK, it's good now.
