### ISSUE TITLE
Compile error on Ubuntu 16.04

### ISSUE THREAD

**Issue by rbreckenridge** [charlesfleche/lpd8-editor#16]
I'm getting this error when I run make on Ubuntu 16.04 --- any thoughts?

```
robb@skippy:~/src/lpd8-editor$ sudo make
g++ -c -m64 -pipe -Werror -O2 -Wall -W -D_REENTRANT -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -Isrc -I/usr/include/alsa -I. -I. -o main.o src/main.cpp
In file included from src/main.cpp:2:0:
src/mainwindow.h:26:42: error: ‘QModelIndex’ does not name a type
     void on_programsView_activated(const QModelIndex&);
                                          ^
Makefile:281: recipe for target 'main.o' failed
make: *** [main.o] Error 1
robb@skippy:~/src/lpd8-editor$

```

**Comment by charlesfleche** [comment]
Hi Robb, and thanks for giving lpd8-editor a go.
First, you should probably not try to compile as root with `sudo`, there is no point really to do so.
Second, lpd8-editor is developed on qt5. It seems like you try to compile against qt4. You should try to install qt5 (on my Kubuntu 17.04, the package is called `qt5-default`), then run the updated version of `qmake` before `make`.

**Comment by rbreckenridge** [comment]
Aw yeah. (I'm logged in as "robb", not "root".) 

I was totally missing a few dependencies, got it working and life's groovy. 

Thanks, this is a great app.

**Comment by charlesfleche** [comment]
Cool, I'm happy it worked for you. Please be in touch if you require further assistance.
