### ISSUE TITLE
La construction plante (Build failed)

### ISSUE THREAD

**Issue by trebmuh** [charlesfleche/lpd8-editor#18]
Bonjour Charles.

J'étais en train d'essayer de construire un paquet deb pour LibraZiK-2, et l'empaquetage plante pour l'instant avec:

```
src/commands.cpp: In member function 'virtual void CreateProgramCommand::redo()':
src/commands.cpp:44:35: error: 'setObsolete' was not declared in this scope
     setObsolete(m_program_id == -1);
                                   ^
src/commands.cpp: In member function 'virtual void CreateProgramCommand::undo()':
src/commands.cpp:50:54: error: 'setObsolete' was not declared in this scope
     setObsolete(!m_model->deleteProgram(m_program_id));
                                                      ^
src/commands.cpp: In member function 'virtual void DeleteProgramCommand::redo()':
src/commands.cpp:68:54: error: 'setObsolete' was not declared in this scope
     setObsolete(!m_model->deleteProgram(m_program_id));
                                                      ^
src/commands.cpp: In member function 'virtual void DeleteProgramCommand::undo()':
src/commands.cpp:75:35: error: 'setObsolete' was not declared in this scope
     setObsolete(m_program_id == -1);
                                   ^
src/commands.cpp: In member function 'virtual void UpdateProgramFromSysexCommand::redo()':
src/commands.cpp:129:43: error: 'setObsolete' was not declared in this scope
     setObsolete(!setSysexAndKeepPrevious());
                                           ^
src/commands.cpp: In member function 'virtual void UpdateProgramFromSysexCommand::undo()':
src/commands.cpp:135:43: error: 'setObsolete' was not declared in this scope
     setObsolete(!setSysexAndKeepPrevious());
                                           ^
Makefile:447: recipe for target 'commands.o' failed

```

En lisant #8, j'ai vérifié et j'ai donc un Qt 5.7.1 (version qt5 de base pour debian stretch). Je ne suis pas codeur, mais je me demande si ça ne serait pas la cause.

Si c'est bien ça, y aurait-il un moyen pour toi de rendre ce logiciel compatible avec Qt 5.7.1 ? Car je ne compte pas jouer avec la pile Qt5 de Debian Stretch et suis donc bloqué pour le moment pour intégrer ce logiciel dans LibraZiK-2.

**Comment by charlesfleche** [comment]
Hello Olivier,
D'abord, super merci pour jeter un oeil à l'empaquetage: tu crois qu'on pourrait merger ton code directement dans lpd8-editor quand ca fonctionnera ? C'était juste après sur ma liste...
Ensuite: oui, carrèment, je vais essayer de faire en sorte que ca compile sur Stretch. C'est un problème de version de Qt, mais ca va se régler facilement. Je te fais ca au plus vite.

**Comment by trebmuh** [comment]
> D'abord, super merci pour jeter un oeil à l'empaquetage: tu crois qu'on pourrait merger ton code directement dans lpd8-editor quand ca fonctionnera ? C'était juste après sur ma liste...

Avec plaisir si tu penses que c'est utile.

>  Ensuite: oui, carrèment, je vais essayer de faire en sorte que ca compile sur Stretch. C'est un problème de version de Qt, mais ca va se régler facilement. Je te fais ca au plus vite.

Super. N'hésite pas à me bipper ici lorsque c'est prêt.

**Comment by charlesfleche** [comment]
Ca devrait compiler sous Debian au tag https://github.com/charlesfleche/lpd8-editor/tree/v0.0.7 maintenant.
Je pense qu'il va falloir exporter tes programmes, supprimer le dossier ~/.local/share/lpd8-editor et réimporter les programmes: je n'ai pas encore de support pour la migration.

**Comment by trebmuh** [comment]
@charlesfleche ça compile ce coup-ci, merci pour le boulot. Je peux le lancer depuis un terminal et l'interface graphique s'affiche bien.

Malheureusement, je ne dispose pas de ce matériel et ne peut pas le tester plus en avant. Aurais-tu par hasard la possibilité de tester mon paquet sur une LibraZiK-2 ou une Debian Stretch ?

**Comment by charlesfleche** [comment]
Oui, je peux tester sur une Stretch.

**Comment by trebmuh** [comment]
Super. Message envoyé en privé.
