### ISSUE TITLE
Montée très forte en utilisation CPU

### ISSUE THREAD

**Issue by trebmuh** [charlesfleche/lpd8-editor#23]
En jouant un peu avec l'IGU, suite à  #18 , je m'aperçois de quelque chose.

Reproduction pas à pas:

- lancer lpd8-editor depuis un terminal
- cliquer sur le menu déroulant où est écrit "Disconnect"
- choisir une des options (j'ai "Disconnect" et "MIDI through port-0")

Résultats :

- le ventilateur commence a tourner rapidement
- j'ai tout un tas de `Cannot disconnect to 129 0` dans le terminal
- une montée rapide de l'utilisation CPU : 2 processus: lpd8-editor à environ 80%, et mate-terminal à environ 70% (sur un bi-cœur)
- l'interface graphique de lpd8 ne répond plus et il me faut le Ctrl+C pour fermer le logiciel

Ça ressemble à un bogue et, c'est pas très grave quand il est lancé par un terminal car on peut le Ctrl+C (et les utilisateurs utilisant le terminal savent ça généralement), mais c'est plus embêtant si je lui fait un élément dans le menu car il faut alors un moyen de le tuer (xkill, ou une applet de gestion des processus,... ce qui n'est pas très connu par les utilisateurs finaux généralement).

**Comment by charlesfleche** [comment]
Bizarre, je vais voir si je peux repro ici.

**Comment by charlesfleche** [comment]
Impossible de reproduire sur une Stretch dans une machine virtuelle, ni sur Kubuntu 17.10. Comment est-ce que tu as compilé l'executable ?

**Comment by charlesfleche** [comment]
Je viens de publier une v0.0.8 qui corrige un mauvais contrôle de valeur de retour d'alsa. Pas certain que ca ne resolve le problème cependant.

Avant de choisir un périphérique dans le menu déroulant, que donne la sortie de `$ aconnect -l` ?

**Comment by trebmuh** [comment]
> Comment est-ce que tu as compilé l'executable ?

Simplement un `qmake` et un `make` (j'ai essayé une simple compilation dans un terminal sans empaquetage pour ce fil de discussion).

> Je viens de publier une v0.0.8 qui corrige un mauvais contrôle de valeur de retour d'alsa. Pas certain que ca ne resolve le problème cependant.

Ça ne le corrige pas.

> Avant de choisir un périphérique dans le menu déroulant, que donne la sortie de `$ aconnect -l` ?

avant de lancer lpd8-editor, j'ai ceci :
```
client 0: 'System' [type=noyau]
    0 'Timer           '
    1 'Announce        '
        Connexion À: 129:0
client 14: 'Midi Through' [type=noyau]
    0 'Midi Through Port-0'
        Connexion À: 129:0[real:1]
        Connecté Depuis: 129:0
```
après avoir lancé lpd8-editor, j'ai ceci :
```
client 0: 'System' [type=noyau]
    0 'Timer           '
    1 'Announce        '
        Connexion À: 129:0, 128:0
client 14: 'Midi Through' [type=noyau]
    0 'Midi Through Port-0'
        Connexion À: 129:0[real:1]
        Connecté Depuis: 129:0
client 128: 'lpd8-editor' [type=utilisateur,pid=478]
    0 'lpd8-editor     '
        Connexion À: 129:0[real:1]
        Connecté Depuis: 0:1, 129:0
```

... et dans le terminal à partir duquel j'ai lancé lpd8-editor, j'ai ceci :
```
Opening MIDI sequencer
Enabling MIDI poll descriptor 0
```

Et après avoir choisi un périphérique dans le menu déroulant, j'ai toujours ceci :
```
client 0: 'System' [type=noyau]
    0 'Timer           '
    1 'Announce        '
        Connexion À: 129:0, 128:0
client 14: 'Midi Through' [type=noyau]
    0 'Midi Through Port-0'
        Connexion À: 129:0[real:1]
        Connecté Depuis: 129:0
client 128: 'lpd8-editor' [type=utilisateur,pid=478]
    0 'lpd8-editor     '
        Connexion À: 129:0[real:1]
        Connecté Depuis: 0:1, 129:0
```

... et  le terminal à partir duquel j'ai lancé lpd8-editor, me balance des lignes et des lignes de `Cannot disconnect to 129 0` sans s'arrêter.

**Comment by trebmuh** [comment]
Ahah, info probablement intéressante : dans mes tests, j'avais Cadence (et jackdbus donc) de lancés. Je viens d'essayer (par intuition) de tuer cadence, jackdbus, et je n'ai plus ce `Cannot disconnect to 129 0`. En affinant un peu, c'est lorsque le _**pont JACK - ALSA-MIDI**_ est activé que les `Cannot disconnect to 129 0` apparaissent.

Je n'ai pas le temps de continuer les investigations maintenant. J'espère que ces remarques ont du sens pour toi.

**Comment by charlesfleche** [comment]
Je ne connais pas cadence, je vais regarder ca.

**Comment by trebmuh** [comment]
Je viens d'essayer avec un lancement de jackd par l'intermédiaire de qjackctl.
Résultat : un lancement de base, et ça fonctionne (pas de `Cannot disconnect to 129 0`), mais si je lance jackd avec qjackctl normalement, puis que dans un terminal, je lance `a2j -e` (le pont MIDI JACK<->ALSA), alors les `Cannot disconnect to 129 0` apparaissent.

**Comment by charlesfleche** [comment]
OK, super, je vais regarder ca.

**Comment by charlesfleche** [comment]
OK, j'arrive à reproduite le bug, je vais essayer de corriger ca.

**Comment by trebmuh** [comment]
:+1:

**Comment by trebmuh** [comment]
:+1: 

Tiens moi au jus et je retesterai ça.

**Comment by charlesfleche** [comment]
Ca devrait réparé dans la v0.0.9: il s'agissait d'un comportement qui n'est pas documenté dans alsa, je vais contacter les dévs pour voir ce qu'ils en pensent.
