### ISSUE TITLE
Compilation échouée (build failed)

### ISSUE THREAD

**Issue by trebmuh** [charlesfleche/lpd8-editor#24]
En essayant de compiler la 0.0.9 (toujours LibraZiK-2 basée sur Debian Stretch), la compilation donne ceci :
```
src/midiconnectionsmodel.cpp: In member function 'void MidiConnectionsModel::disconnectAllPorts() const':
src/midiconnectionsmodel.cpp:151:69: error: lvalue required as increment operand
             const int idx = ++snd_seq_query_subscribe_get_index(subs);
                                                                     ^
src/midiconnectionsmodel.cpp:164:69: error: lvalue required as increment operand
             const int idx = ++snd_seq_query_subscribe_get_index(subs);
                                                                     ^
Makefile:472: recipe for target 'midiconnectionsmodel.o' failed
make[1]: *** [midiconnectionsmodel.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/build/lpd8-editor-0.0.9'

```

**Comment by charlesfleche** [comment]
Ah, problème de version de compilateur... Je regarde ca.

**Comment by charlesfleche** [comment]
`master` devrait compiler maintenant. Je vais essayer de faire plus attention à stretch maintenant.

**Comment by trebmuh** [comment]
Ça compile, merci.

J'ai mis un .deb de cette nouvelle version au même endroit que précédement. Si tu peux tester que ça fonctionne, c'est chouette, je pourrais le publier ce week end.

Et je te ferai un PR pour les règles de construction pour Debian.

**Comment by trebmuh** [comment]
@charlesfleche : ça compile, merci.

Je l'ai lancé et [le bogue précédent de boucle infinie](https://github.com/charlesfleche/lpd8-editor/issues/23) a disparu. Bravo !

J'ai mis un .deb de cette nouvelle version au même endroit que précédement. Si tu peux tester que ça fonctionne avec un vrai lpd8, c'est chouette car je pourrais le publier dans la mise à jour hebdomadaire de ce week end.

**Comment by charlesfleche** [comment]
OK, je tente et si ca passe je taggerai une nouvelle version

**Comment by trebmuh** [comment]
OK. Tiens moi au jus.

**Comment by charlesfleche** [comment]
Bon la v0.010 compile sur Debian, ne bouffe plus tout le CPU en cas de bug,
fonctionne avec un vrai LPD8, a le chemin d'install par défaut de changé et
j'ai corrigé un dernier bug graphique gênant. Ca devrait être bon ta
release de ce week-end.

J'aimerai bien intégrer les scripts de création de paquet pour Debian pour
à terme mettre lpd8-editor directement dans Debian. Tu en penses quoi ?

2018-04-05 18:04 GMT+02:00 Olivier Humbert <notifications@github.com>:

**Comment by trebmuh** [comment]
@charlesfleche : c'est fait ici https://github.com/charlesfleche/lpd8-editor/pull/25 d'après un réempaquetage que je viens de faire pour la version 0.0.10 .

Les paquets deb binaires sont au même endroit que d'habitude, si tu peux faire un test rapide, c'est chouette car j'ai modifié quelques petits trucs depuis le dernier paquet. Entre autres, la dépendance à qt5-sql, et l'ajout d'un élément de menu (fichier desktop + image).

Si tu as le temps de me tenir au jus aujourd'hui, je pourrais le passer directement dans le dépôt utilisateur de LibraZiK-2, sinon il restera une semaine de plus dans le dépôt de tests, c'est pas grave.

**Comment by charlesfleche** [comment]
Ah, je vais essayer tes paquets, mais je vais être loin de mon LPD8 pendant deux semaines.

**Comment by charlesfleche** [comment]
Le paquet v0.0.10 pour amd64 a l'air de fonctionner. Je nai pas testé avec un LPD8, mais un sniffer MIDI recoit bien les messages, du coup je pense que c'est bon, là.

**Comment by trebmuh** [comment]
OK, chouette. Merci pour le retour. Je le publierai la semaine prochaine dans LibraZiK-2 du coup.
