### ISSUE TITLE
Traduction

### ISSUE THREAD

**Issue by trebmuh** [charlesfleche/lpd8-editor#29]
Super d'avoir ouvert le logiciel à la traduction !

J'ai deux remarques que j'espère constructives.

  1. j'ai vu que tu mettais le fichier qm (binaire) dans les sources. Je conseille de ne pas le faire et de ne mettre que le fichier ts (texte) et de construire le fichier binaire lors du build
  2. j'ai vu que tu installais le fichier qm avec le debian/install. C'est pas faux de faire ça, mais c'est un contournement. Le fichier .pro devrait installer ce fichier correctement, ce qui permettrait à tous les utilisateurs d'installer le fichier qm (et pas uniquement ceux de Debian).

En espérant que ça aide.

**Comment by charlesfleche** [comment]
1. Oui, je suis d'accord, et c'est prévu pour plus tard quand j'aurais réparé le build pour debian et mis en place le serveur de CI.

2. Pour l'instant les makefiles ne s'occupent pas du tout du build des traductions, donc l'install doit se faire à la main. Ca changera par la suite.

**Comment by trebmuh** [comment]
OK
