### ISSUE TITLE
2 chaînes non-traduites

### ISSUE THREAD

**Issue by trebmuh** [charlesfleche/lpd8-editor#34]
Alors que le reste de la traduction est complète, les 2 éléments dans le "menu -> Aide" ("About", et "About Qt") reste en anglais bien qu'ils semblent être traduits dans le fichier .ts

**Comment by trebmuh** [comment]
Ping de remontée.

**Comment by charlesfleche** [comment]
Fixed in 95769f5cfc5c258a5b5221215cfcae611bcc8dd9
