### ISSUE TITLE
Build fails with alsa-lib >= 1.1.9

### ISSUE THREAD

**Issue by schnitzeltony** [charlesfleche/lpd8-editor#36]
Seems alsalib wants to change directory layout:

>  #warning This header is deprecated, use <alsa/asoundlib.h> instead.
>   ^~~~~~~
> In file included from ../../git/src/midiconnectionsmodel.h:7,
>                  from ../../git/src/midiconnectionsmodel.cpp:1:
> 

Since common.pri sets -Werror this ends as an error.

**Comment by charlesfleche** [comment]
Oh ! Thanks @schnitzeltony 
First, `-Werror` shouldn't be activated in Release mode, to avoid this kind of problem. Sorry about that.
May I know what distribution you are trying building lpd8editor against ? Thanks

**Comment by schnitzeltony** [comment]
It is  Openembedded/Yocto [1] and the layer is meta-musicians [2]

[1] https://www.yoctoproject.org/
[2] https://github.com/schnitzeltony/meta-musicians

**Comment by charlesfleche** [comment]
I already love your project !

I can't try right now, but I think that enclosing the `-Werror` line in a `CONFIG()` should be activating the flag for debug builds only.

In https://github.com/charlesfleche/lpd8editor/blob/master/common.pri :

``` qmake
QMAKE_CXXFLAGS += -Werror
```

becomes :

``` qmake
CONFIG(debug, debug|release) {
    QMAKE_CXXFLAGS += -Werror
}
```

Would you mind to give that a go ? If it works as you expect, would you mind to PR it ? Thanks

**Comment by charlesfleche** [comment]
The include warning should be fixed now and lpd8editor should compile against alsa 1.1.9 now. I'm closing this bug. Thanks again for the report, @schnitzeltony
