### ISSUE TITLE
[Question] Use theLPD8 for simle volume control on Linux Mint MATE

### ISSUE THREAD

**Issue by friesenkiwi** [charlesfleche/lpd8-editor#39]
Hi, I have a slightly off-topic question, which I hope you would be able to answer:

I have an LPD8 Wireless here and I would like to use it (not BT, only via USB) for very simple volume control in the standard Linux sound system, no music or sound production at all. I would like to control the volume of a specific program (VLC) via one of the turn knobs (say, K1) on the LPD8.
How would that be possible? VLC shows up in the default sound control/mixer as an application with it's own volume and that's the volume slider I would want to control via the hardware knob. I imagine there could be some kind of very simple configuration tool, because everything I find on the web seem to be much more advanced DAWs etc. for music production.

Thanks in advance and sorry to bother you here :-/
Cheers

**Comment by charlesfleche** [comment]
My guess would be to use a third party software that would:
- listen to Midi messages on one end
- set volume commands to PulseAudio
This purpose is outside of the scope of lpd8editor, but it looks like someone does something very similar with an nanoKontrol2: https://github.com/solarnz/pamidicontrol
It seems to be reasonably configurable, I'd expect it to work out of the box with an LPD8
