### ISSUE TITLE
Instructions need updating

### ISSUE THREAD

**Issue by TygerTung** [charlesfleche/lpd8-editor#43]
Hi, I spent several hours trying to get this working last night. I'm on Ubuntu Studio 18.04

I downloaded this programme and tried to get it working. There looks like there might be an executable in the "debian" folder but it didn't seem to work.

I then tried to follow the instructions to build the programme from code:

Build, test and run
`$ cd lpd8editor
$ qmake
$ make
$ make check
$ sudo make install
$ /usr/bin/lpd8editor`

But it wouldn't work as it couldn't find any make file.
I worked out this morning that the terminal should be in this folder for it to work:

`lpd8editor-master/src`

When I changed to that folder it seems to work now.
I will just have to work out how to add it to my programmes menu.

Thanks very much for writing this software!

Cheers,

Sam

**Comment by charlesfleche** [comment]
Thanks for your interest in this small project. Look at the README again, the build instruction should be up to date and lpd8editor should be easier to build now.
