### ISSUE TITLE
Compile instructions for release tar unclear

### ISSUE THREAD

**Issue by diovudau** [charlesfleche/lpd8-editor#45]
Hello,

I would like to compile your software from release 0.0.15 https://github.com/charlesfleche/lpd8editor/releases/tag/v0.0.15
However, the README ones are for the git version and do not work. 

Could you please provide compile instructions for the release tar?  It doesn't have to be in a fancy way in the readme, just a short version here would be finde.

**Comment by charlesfleche** [comment]
The README should be more clear for tarball build now. Do you manage to build it now ?
Our of curiosity, why do you want to build from the source archive ? Two binaries are published, one for generic linux, the other for debian based system: do you experience incompatibilities with your system ?

**Comment by diovudau** [comment]
Thanks for the update. I will try soon.

Binaries for Open Source Linux programs are odd. Why would I need them.  For testing and development, as programmer or power user,  one can compile themselves. For convenience there are distribution packages.

It's also a trust issue. With premade binaries you never know what's inside.

**Comment by diovudau** [comment]
The README is still wrong, btw, both for git and release.

`cmake ../lpd8editor`...
and
`cmake ../lpd8editor-x.y.z`...

should be just
`cmake ../`
Because you are just one directory up, in the build dir.

The tarball does not build for me, btw. A Cmake error.  I can compile and run from git clone though.

```
cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/lpd8editor
-- Trying to get a version from git describe
fatal: not a git repository (or any of the parent directories): .git
CMake Error at CMakeLists.txt:19 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.

-- Git describe version:
-- Parsed git describe version:
-- The CXX compiler identification is GNU 11.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib/ccache/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Project version: 0.0.0
-- QApplication version:
-- Configuring incomplete, errors occurred!

```

**Comment by charlesfleche** [comment]
> Because you are just one directory up, in the build dir.

No, I don't think we are: just above there is a `cd build-lpd8editor`. That warrants the `cmake ../lpd8editor`.

> The tarball does not build for me, btw. A Cmake error. I can compile and run from git clone though.

Try v0.0.16

**Comment by diovudau** [comment]
I see, because you don't instruct to go into the cloned git dir. I did that by habit without noticing.

That said, my advice is to actually go into the git dir, and create the build dir there, to keep it all contained.
This also removes the need of the user to rewrite the command from the readme with the version number.

**Comment by cbix** [comment]
The logic in #46 is still wrong, as it checks for `LPD8EDITOR_QAPPLICATION_VERSION` which is hardcoded as `0.0.0` in the beginning.

Ideally, the CMakeLists should respect a possible user-provided `CMAKE_PROJECT_VERSION` and not have `find_package(Git REQUIRED)`.
