### ISSUE TITLE
Ubuntu 15.10 Compilation issue on QT5

### ISSUE THREAD

**Issue by harryhaaren** [charlesfleche/lpd8-editor#8]
Hi!

I'm having issues compiling on Ubuntu 15.10:

```
$ qmake
Project MESSAGE: Warning: unknown QT: qml
Project MESSAGE: Warning: unknown QT: quick
```

And then 
```
$ make
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -Isrc -I/usr/include/alsa -I. -o main.o src/main.cpp
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -Isrc -I/usr/include/alsa -I. -o application.o src/application.cpp
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -Isrc -I/usr/include/alsa -I. -o utils.o src/utils.cpp
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -Isrc -I/usr/include/alsa -I. -o qmltablemodelproxy.o src/qmltablemodelproxy.cpp
src/utils.cpp:4:26: fatal error: QStandardPaths: No such file or directory
compilation terminated.
Makefile:289: recipe for target 'utils.o' failed
make: *** [utils.o] Error 1
```

Is this a QT5 misconfiguration issue on my end? I've done a quick check to ensure that `qtbase5-dev` and that `qtdeclaratives5-dev` are installed, they are but no joy.

Any ideas? Thanks, -Harry

**Comment by charlesfleche** [comment]
First : many thanks to take the time to download and try to compile this. Seriously, many thanks.

You need a pretty recent Qt to run compile this : Qt 5.8, which is the latest version. You can probably try to download the latest Qt SDK and try from there.
https://www.qt.io/download-open-source/

**Comment by harryhaaren** [comment]
To convince Ubuntu to *actually* use QT5, it is required to install the `qt5-default` package[1].  QT 5.4.x is available on Ubuntu 15.10, so its not quite the 5.8 as required by this app... but I tried it anyway! After encountered the #9 problem, I happily commented out that line... until this:
```
RCC Parse Error: 'src/qtquickcontrols2.conf' Line: 1 Column: 1 [Start tag expected.]
```
Actually got angry. Updating the `.conf` file didn't really help.. so I removed it from the `lpd8-editor.pro` file (the RESOURCE section). This allowed a compile, but running the binary doesn't result in a UI showing, with various messages like this:
```
qrc:/main.qml:1 module "QtQuick.Controls" is not installed
```
So some package installation 
```
apt-get install qml-module-qtquick-controls
apt-get install qml-module-qtquick2
...
```
And it finally barfs with this error:
```
qrc:/main.qml:1 module "QtQuick" version 2.7 is not installed
```
So I guess I better *actually* use QT 5.8 like I'm told to do by the README :D

That's for another day - its late here! -H

[1] https://launchpad.net/ubuntu/wily/+package/qt5-default

**Comment by charlesfleche** [comment]
@harryhaaren @erwan35 I'm trying to setup a chat so we can try sort out these compilation issues together. I'll keep you updated when it's live.

**Comment by charlesfleche** [comment]
Here it is : https://gitter.im/lpd8-editor/Lobby
I'm in Mexico at the moment.

**Comment by charlesfleche** [comment]
@harryhaaren We've had success with @erwan35 to build and run lpd8-editor by downloading the SDK. I'm going to add better build doc whenever I get the chance but meanwhile I'll be happy to help you directly if required. Please drop by the gitter channel (or an IRC channel you'll find suitable) if you can and we'll see what we can do.
