### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by erwan35** [charlesfleche/lpd8-editor#9]
Hello,

On my side i'm getting this: 

erwan@menhir:~/lpd8-editor$ make
g++ -c -m64 -pipe -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB -I. -Isrc -isystem /usr/include/alsa -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o main.o src/main.cpp
src/main.cpp: In function ‘int main(int, char**)’:
src/main.cpp:10:36: error: ‘AA_EnableHighDpiScaling’ is not a member of ‘Qt’
     QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
                                    ^
Makefile:421: recipe for target 'main.o' failed

Cheers
Erwan

**Comment by charlesfleche** [comment]
Many thanks @erwan35 for trying to compile this, really appreciated. I think your problem is same than #8 : you probably trying to compile against a not recent enough Qt. I'm going to close this issue, and we'll continue the discussion in #8 if you don't mind.
